name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust (for stylua)
        uses: dtolnay/rust-toolchain@stable
      - name: Install stylua
        run: cargo install stylua
      - name: Check formatting with stylua
        run: make fmt-check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Lua and Luacheck
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.1 luarocks
          sudo luarocks install luacheck
      - name: Run Luacheck
        run: luacheck lua tests plugin

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Install Lua and Luarocks Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.1 luarocks
          # Install busted and luacov locally
          luarocks install --local busted
          luarocks install --local luacov
      - name: Add local luarocks bin to PATH
        run: echo "${HOME}/.luarocks/bin" >> $GITHUB_PATH
      - name: Run tests with coverage
        env:
          LUA_PATH: "./lua/?.lua;./lua/?/init.lua;${LUA_PATH}"
        run: busted tests --coverage
      - name: Generate coverage report
        run: luacov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: zhisme/copy_with_context.nvim
