name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust (for stylua)
        uses: dtolnay/rust-toolchain@stable
      - name: Install stylua
        run: cargo install stylua
      - name: Check formatting with stylua
        run: make fmt-check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Lua and Luacheck
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.1 luarocks
          sudo luarocks install luacheck
      - name: Run Luacheck
        run: luacheck lua tests plugin

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Install Lua, Luarocks, and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.1 luarocks
          luarocks install busted
          luarocks install luacov
      - name: Run tests with coverage
        run: busted tests --coverage
      - name: Generate coverage report
        run: luacov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: luacov.report.out
          token: ${{ secrets.CODECOV_TOKEN }}
